import Navbar from "@/components/Navbar"
import TodoForm from "@/components/TodoForm"
import { cn } from "@/lib/utils"
import { ThemeProvider } from "next-themes"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={cn(
					"flex h-screen w-screen items-center justify-center",
					inter.className
				)}
				suppressHydrationWarning
			>
				<main className="flex h-screen w-screen justify-center p-4">
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						<div className="relative flex w-full max-w-md flex-col overflow-hidden md:rounded-md md:border md:border-neutral-500">
							<Navbar />

							<div className="flex h-navScreen w-full flex-col overflow-hidden">
								{children}
								<div className="flex w-full p-4">
									<TodoForm />
								</div>
							</div>
						</div>
					</ThemeProvider>
				</main>
			</body>
		</html>
	)
}
